# Configuration for https://github.com/wei/pull
version: "1"
rules:
  - base: master
    upstream: openeemeter:master
    mergeMethod: hardreset
    mergeUnstable: true  # Merge PRs even if their GitHub Actions workflows are failing
